info:
  component: demo-tk-account-api
  
server:  
  port: 8080

spring:
  application:
    name: demo-tk-account-api
  jersey:
    type: filter
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/demo_accounts_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: abc123
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      idleTimeout: 15000
      minimumIdle: 5
      maximumPoolSize: 10
      connectionTimeout: 20000
      poolName: demo-tk-account-api-pool
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: create
  jackson:
    serialization:
      indent-output: true

application-config:
  mode: local
  wiremock: true
  wiremockPort: 9998
  version: 1.0
